### ISSUE TITLE
several workbooks unintentionally open in edit mode?

### ISSUE THREAD

**Issue by gardnerjr** [Microsoft/Application-Insights-Workbooks#127]
these templates have `"isLocked": false`, so when they open from the gallery they open in edit mode.  is this correct?

* Workbooks/Virtual Machines/Key Metrics/Key Metrics.workbook
* Workbooks/Usage/Usage Calendar/Usage Calendar.workbook
* Workbooks/Azure Active Directory/SignIns/SignIns.workbook
* Workbooks/Azure Active Directory/SignInsUsingLegacyAuth/SignIns.workbook
* Workbooks/Azure Active Directory TroubleShooting/SignInFailureAnalysis/SignInFailureAnalysis.workbook
* Workbooks/Azure Active Directory/SignInsAndConditionalAccess/SignInsAndConditionalAccess.workbook

**Comment by andrewki-msft** [comment]
I suggest the test be updated to throw a warning if `isLocked` is `false`

**Comment by acearun** [comment]
The fix here was to take out the isLocked flag from the advanced editor by default since most templates don't need to open in Edit mode. If needed, an author will need to add in the property in the workbook payload.

The active directory templates have been fixed. Will fix the Usage Calendar template too.
