### ISSUE TITLE
Missing workbook language reference guide

### ISSUE THREAD

**Issue by velociwabbit** [microsoft/Application-Insights-Workbooks#1770]
I have been struggling to make use of workbooks for any but the simplest of tasks. This is largely due to the fact that there is no language reference guide that would afford the user the ability to specify "type" and other parameters in a meaningful way. Last time I checked type 0 type 2 type 9 etc are not Microsoft standard ways of naming things and have not been since ms-dos.

Yet here they are in each workbook as it to tell us that they are necessary but we are going to give you any more info about them.

I am really hoping that Microsoft is not up to its old tricks again by selectively providing info that gives the user a distinct disadvantage while creating workbooks on azure data.

For example, while it is clear how to use parameters in kql queries it is not clear how to conditionally show various dropdowns as a function of previous dropdown selections.  This conditional display is critical to our ability to make appInsights workbooks customizable for each of our spa's requirements.  The docs do not appear to have a solution to this very common problem.

Dropdown a value requires the display of dropdown b or dropdown c... which then requires dropdown e or dropdown f.  
The conditional display values do not appear to work in such a scenario.

And there does not appear to be any docs about how to do this.

I have downloaded the entire corpus of documentation that is many thousand pages and at best disorganized and incomplete.
very disappointing indeed

**Comment by velociwabbit** [comment]
Also whoever is in charge of the online docs for this particular product should be moved into the "creating badly worded  puzzles  for Xbox " division and out of their present position

Giving an abstract example not grounded in a specificity actionable and complete set of code is the equivalent of someone giving a PPT presentation with a bunch of arm-waving and then right before closing the presentation a small box in the corner of the last page that says "Miracle occurs here".   

As it stands right now the docs are an insult to professionals who spend money on azure and expect not to have to waste time on sub standard work by the Azure docs team.

**Comment by velociwabbit** [comment]
Here is another very simple request. 

Depending upon which tables are selected I want the viewer to be able to select the columns they want.... This is available in the log query function but I cannot find an example of how to construct one (that has the dependency of other dropdowns) anywhere.  

I am glad that Microsoft uses this functionality all over the place... bit disappointed that i have to write this request

**Comment by gardnerjr** [comment]
Workbooks are generally intended to be created using the Workbooks UX, where a lot of this information is opaque to users.  The JSON format is the serialized format when a workbook is saved, and is only partially documented at the current time because of time and resource constraints.  Numeric enums, while not super discoverable, are a very common construct, even still today.

> it is not clear how to conditionally show various dropdowns as a function of previous dropdown selections

It is not clear because it is not directly possible at the current time.  Individual parameters cannot be dynamically hidden and shown, though it is a request on our backlog.  Only steps have conditional visibility at this time, so a workaround may be to create different parameter steps, containing the parameters that apply or do not apply depending on the situation.

>  I want the viewer to be able to select the columns they want.

Also on our list, though is also (unfortunately) not very common in the Azure portal, and (because) it is not built into the portal's grid control itself.

I understand your concerns and frustrations.  Do you have a specific concrete docs thing we can fix?  Many of the examples are abstract because the actual data available in any log analytics workspace or metrics for any resource aren't valid in other places, so many concrete examples aren't easily portable.  We're working on trying to improve these things, so the more specifics you can give, the higher the chance we can address them.

**Comment by velociwabbit** [comment]
I have many that I can provide but it would be faster for you to go through the workbook and kql online docs and review them for exact answers with actual working code (in a workbook or kql format that is complete as opposed to a theoretical snippet).

Over time i will gladly provide you with a list. But I am working as a consultant to a sp500 company with all the accompanying security etc on azure.

I truly mean this with no rancor... get someone who knows how to build reference documentation for workbooks and kql. 

If you do this you will quadruple   use of this burgeoning technology.

The potential for workbooks and kql to be the standard templating language for cloud administration (the equivalent to .bat files in ms dos ) is yours to lose.

As it stands right now I am going to have to advise my client not to invest too much in this technology because it is not getting the attention it needs at ms and azure.

 If this technology is implemented correctly all of azure could be built on it.

It is what I assumed was happening behind the scenes.

The thing is that it is not even that hard to build. I have built an HTML / SQL server full stack react generator in 6 months that does 90% of the non kql parts plus 3d web/gl graphics

I would offer to sell  or give it to you but I know how ms internally operates and it would take legions and millions of dollars just to find the person who has the authority to say yes

what a shame
