### ISSUE TITLE
Pinning issues

### ISSUE THREAD

**Issue by nosalan** [microsoft/Application-Insights-Workbooks#407]
1) How do I select dashboard when pinning? It pins the workbook to a dashboard I dont want, but cant select anything else
2) Why is dropdown with parameters not able to be pinned do dashboard?
3) How to integrate the time settings on the Application Dashboard with the workbook query time range?

Btw, is the Workbook feature being abandoned soon? I see it's quite unstable and some feature were promised to be added but there aren't, like unstacked barchart columns

**Comment by gardnerjr** [comment]
1. For pinning, currently there's no way for us to give you the option to pick a dashboard when pinning. We depend on the portal itself for this support, which we've asked for.  It is represented here: https://feedback.azure.com/forums/223579-azure-portal/suggestions/20238709-pin-to-dashboard-allow-selection-of-dashboard-wh

2.  Not sure the question here.  you want to pin a dropdown to the dashboard?  the portal itself doesn't really have that concept on their dashboards.  they do have filter support, and we have some ideas on allowing parameters from workbooks to possibly show up as filters on a dashboard, but that work hasn't been done yet.  Do you have a specific example?

3.  If a workbook uses a [time range parameter](https://github.com/microsoft/Application-Insights-Workbooks/blob/master/Documentation/Parameters/Time.md), any parts in that workbook that are pinned will use the dashboard's time range as the value of that parameter.  
    - So if you create a workbook that has a time range parameter, and a query that uses that time range parameter, either by selecting it in the dropdown or by using the `{parameter}` syntax inside the query text, changing the *dashboard's* time range will update that query.  or likewise, if you use a metrics step and pick the time range parameter, that pinned metrics item will update when the dashboard timerange updates
    - if the query/metric has *hardcoded* time ranges, when pinned, the hardcoded timeranges will still apply.  (especially in queries where we don't want to modify the behavior of queries when we don't know how time ranges are being used;  that leads to very subtle broken things where the results might look right on the dashboard, but the are not correct)
    - if you look at pinned workbooks parts on an azure dashboard, if it is using the dashboard's time range, it will have a subtitle like "([Last 4 hours] @ [12:30pm]", where the first brackets shows the time range it inherited from the dashboard, and the second part shows the last time that part auto refreshed. (i see today that something about this isn't working and it looks like all the dashboard parts are not properly inheriting the working)

Not sure where the "Abandoned" thing is coming from; Workbooks is growing and appearing in more and more places in the portal.  If you have features you've asked for and want to track, let me know, because i'm not sure that unstacked bar chart has been a specific request to the workbooks team, as I don't see a specific backlog item for it.  If you're internal, contact me internally and I can point you directly to our backlog.  Similarly if there's something unstable, let me know specifically what you are looking at so we can fix it.

**Comment by gardnerjr** [comment]
The pinning with time range parameters issues should all be fixed in prod now.

Need more information on (2) listed above to be helpful.

The option for unstacked bar charts will appear in Workbooks in the portal in the next few days as the Chart Settings features come online.

**Comment by nosalan** [comment]
Regarding 2, I created a workbook with a dropdown that is dynamically populated by a query. The charts in the workbook use that dropdown parameter. I was able to pin the chart to the dashboard but was unable to pin the dropdown to the dashboard. There was no pin icon. It was not a time range parameter. Hope that it exaplains more. Related image is below.

Thanks for the replies. Let me explaing why I thought workbooks are abandoned.
In the first place, I didn't understand why we have Application Insights ->Logs (Analytics) where you can write query and pin resulting chart to the Dashboard (with the ability to select Dashboard) and Workbooks queries. Workbooks allow to create custom dropdowns whereas Logs (Anlaytics) don't allow that. On the other hand Logs have unstacked columns and allow to select the dashboard. So these two seemed to me like overlapping or competing functionalities trying to achieve the same goal. After reading the [msdn answer dated 2 years ago](https://social.msdn.microsoft.com/Forums/vstudio/en-US/0e1afe3f-7498-4ce3-b35f-8e56afcea84c/app-insights-unstacked-chart-on-workbook?forum=ApplicationInsights) about missing unstacked columns support, I thought that if this wasn't implemented so far then maybe Workbooks are not actively developed. As I see I was wrong so thanks for clarification. I still feel Workbooks and Logs (Analytics) should be a single product with custom parameters, all kinds of charts and working on single dashboard.

Regarding ustability, there were several times I went to _Monitor -> Workbooks (preview) -> Recently modified workbooks_ and clicked last of the green icons to edit the workbook. But te page that loaded afterwards was empty. It happens sometimes.


![image](https://user-images.githubusercontent.com/2273250/66492622-02e43080-eab5-11e9-9bc6-fe5bb827ab4f.png)

**Comment by gardnerjr** [comment]
Workbooks and Logs will probably never be a "single" product, as they do different things, and are intended for different things:
* One (logs) is a data source that supports querying data in that one data store
* The other (workbooks) is a generic canvas that lets you query *across* data sources, not just logs (logs, alerts, health, resources, metrics, adx, etc, etc) and create different kinds of interactable things from all those data sources (parameters, grids, charts, metrics, tiles, graphs, tabs, links)

thank you for bringing that msdn item to my attention.  yes, 2 years ago we might not have supported something.  we now support unstacked bars, but not this specific way (we only support them in time charts right now)

if you see specific bugs, post them here as issues with specific details
