### ISSUE TITLE
Field Widths do not save

### ISSUE THREAD

**Issue by AndrewSmithRS** [microsoft/Application-Insights-Workbooks#546]
With a grid output the the field widths seem to be set some arbitrary value sometimes either hiding the field title or the cell content. When adjusting the width manually this does not save. Also when making the field width wider a scrollbar appears as if there is additional hidden content to the right of the visible fields. 

Modifying percent width (even setting to 0) or the maximum width does not have any positive effect.

A good example of this is the Virtual Machines Key Metrics workbook.

**Comment by gardnerjr** [comment]
The portal framework team is actively working on changing the behavior of grid column sizing everywhere in the portal to meet some accessibility requirements.  We've also been following along, trying to fix things in response to their changes as they go.

unfortunately, because of the holiday lockdowns (which were then extended for JEDI), there appear to be a lot of partially deployed things even within the portal framework itself in the MPAC environment.  in those cases, the portal appears to be making all columns uniform width no matter what we tell it to do.

Workbooks attempts to auto size most columns, using the column header width as a starting point.  some of the columns, like bars, timelines, sparks are fixed widths.

if you have specific examples, paste screenshots, etc here with as much details as you can.  Depending on environment, browser, portalfx version, etc, there are a lot of strange cases right now.

**Comment by mortenlerudjordet** [comment]
This is a big problem for us also. We have invested in creating our own workbooks as part of Azure Monitor and there seem to have been an update that made it worse for us. All our workbook using grids have their columns with minimized. So both content and the labels are hidden by the lack of width.

This makes our dev team using them very cranky. As each time opening a complex workbook they have to manually expand the width of the columns to be able to read the content.

**Comment by mortenlerudjordet** [comment]
This is in chrome, where one can see that there is a lot of room for the column information to expand and use the whole real estate available. All columns are set to automatic.
I have also tried to set many of the columns that does not have content I want to display to hidden, though this does nothing for how the width is set.

![WorkbookColumnWidth](https://user-images.githubusercontent.com/10818066/72530097-ea7f7100-386e-11ea-9c34-f5c85ea113bc.png)

This is how it is configured:
![ColumnSettings](https://user-images.githubusercontent.com/10818066/72530231-38947480-386f-11ea-9c5a-087d243a9491.png)

![ColumnLabel](https://user-images.githubusercontent.com/10818066/72530247-3df1bf00-386f-11ea-9559-fb3465dcee48.png)

**Comment by gardnerjr** [comment]
Workbooks does not save the widths of columns, we depend on auto sizing to have useful sizes depending on the data.   

As I stated above, the portal team is changing things underneath us and we're trying to keep up.  We do not know the width of the grid, as it would change based on the size of the window and other content inside.  we don't use percentage widths to fill the whole grid, because in that case you get no ability to have a horizontal scrollbar, and on narrow screens, it would be impossible to stretch out columns to see anything.

Our blackout period has ended, so builds are now "flowing" through the pipeline.  Likewise, the blackout for the portal team itself has ended, so some of their fixes are now also flowing.   Expect behaviors to change, hopefully always getting better.

if later this week you're still seeing issues, let us know.
