### ISSUE TITLE
Allow Pie Chart & others to be interactive

### ISSUE THREAD

**Issue by cbtham** [microsoft/Application-Insights-Workbooks#745]
Hi, I discovered interactive parameters from documentation over here. 
https://docs.microsoft.com/en-us/azure/azure-monitor/platform/workbooks-interactive

When I tried on pie, it was not working. I thought I did something wrong. When I change the visualization to grid, it works. May I know will this be supported in the future? or is there already a preview that supports this. What I'm trying to do is to create a pie chart with a grid after to show interacted clicks on the pie in relative to the grid. There is a donut tile conversion for dashboard that does that. Would like to recreate in workbook

**Comment by gardnerjr** [comment]
When using charts, not all of the fields of the grid are available for export, because the charts generally have to do manipulations of the data to turn it into chart series data.  After that, it might be impossible to resolve a bar in a chart back to a single row in a grid, as many rows might have been combined.

from the [github version of those docs](https://github.com/microsoft/Application-Insights-Workbooks/blob/master/Documentation/Interactivity.md) (emphasis added)
> For grids and tiles, this will be all of the fields in the grid. **For charts, the available fields will be x, y, series, label (depending on the type of chart).**

will need to make sure that gets noted in the public docs.

one trick to see what exactly is available is to leave the `field to export` field blank as a test, and then add a text step below the chart that is bound to the parameter, like `{parameter:json}`.  that will show you all the names of the fields available for export from that chart.
